apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-telemetry-agent
  namespace: testing-todo
  labels:
    app: node-telemetry-agent
    tier: agent
    app.kubernetes.io/managed-by: envscale
spec:
  selector:
    matchLabels:
      app: node-telemetry-agent
  template:
    metadata:
      labels:
        app: node-telemetry-agent
        tier: agent
    spec:
      containers:
        - name: telemetry-collector
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - "while true; do echo '[Agent] Collecting host metrics and node health telemetry...'; sleep 15; done"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
